---
- name: Check Tomcat PID file
  ansible.builtin.stat: path="{{ catalina_base }}/tomcat.pid"
  register: tomcat_pid
  when:
    - catalina_home is defined
  changed_when: false
  tags: stop

- name: Stop Tomcat (with PID file)
  become: true
  become_user: "{{ tomcat_owner }}"
  environment:
    CATALINA_BASE: "{{ catalina_base }}"
    CATALINA_PID: "{{ catalina_base }}/tomcat.pid"
  ansible.builtin.command: "{{ catalina_home }}/bin/catalina.sh stop 30 -force"
  when:
    - catalina_home is defined
    - tomcat_pid is not defined or tomcat_pid.stat.exists
  changed_when: false
  tags: stop

- name: Stop Tomcat (without PID file)
  become: true
  become_user: "{{ tomcat_owner }}"
  environment:
    CATALINA_BASE: "{{ catalina_base }}"
  ansible.builtin.command: "{{ catalina_home }}/bin/catalina.sh stop 30 -force"
  when:
    - catalina_home is defined
    - tomcat_pid is not defined or not tomcat_pid.stat.exists
  tags: stop

- name: Check if war file exists
  ansible.builtin.stat:
    path: "{{ catalina_base }}/{{ kb_webapps }}/ROOT.war"
  register: war
  tags:
    - tomcat_cleanup
    - stop

- name: Clean up Tomcat deployment files
  become: true
  become_user: "{{ tomcat_owner }}"
  ansible.builtin.file:
    path: "{{ catalina_base }}/{{ item }}"
    state: absent
  with_items:
    - "{{ kb_webapps }}/ROOT"
    - work/
  when:
    - catalina_home is defined
    - war.stat.exists
  tags:
    - tomcat_cleanup
    - stop
