---
- name: Setup Ansible ruby interpreter # noqa: no-free-form,var-naming[no-role-prefix]
  set_fact: ansible_ruby_interpreter="{{ kpm_path }}/lib/ruby/bin/ruby"
  tags: common
# Required for ansible-lint: variable must stay named 'ansible_ruby_interpreter' for Ansible to pick it up