---
nexus_url: https://repo1.maven.org
nexus_repository: maven2

kpm_install_dir: /opt
kpm_path: "{{ kpm_install_dir }}/kpm-latest"
kpm_owner: root
kpm_group: root

catalina_home: /usr/share/tomcat
catalina_base: /var/lib/tomcat
tomcat_install_dir: /opt
tomcat_home: "{{ catalina_base }}"
tomcat_owner: tomcat
tomcat_group: tomcat

# Webapps directory : {{ catalina_base }}/{{ kb_webapps }}
kb_webapps: webapps
kaui_webapps: webapps

tomcat_foreground: false

# Base directory for namespacing
kb_install_dir: /var/lib/killbill
# Configuration files (killbill.properties, JRuby files, etc.)
kb_config_dir: "{{ kb_install_dir }}/config"
# Kill Bill plugins and OSGI bundles
kb_plugins_dir: "{{ kb_install_dir }}/bundles"
# kpm.yml file
kpm_yml: "{{ kb_install_dir }}/kpm.yml"
killbill_kpm_yml: "{{ kb_install_dir }}/kpm.yml"
kaui_kpm_yml: "{{ kb_install_dir }}/kpm.yml"

kaui_install_dir: /var/lib/kaui
# For consistency as to where the sha1.yml is located
kaui_plugins_dir: "{{ kaui_install_dir }}/bundles"

flyway_install_dir: /opt
flyway: java -jar {{ flyway_install_dir }}/killbill-flyway.jar -url='{{ lookup('env','KILLBILL_DAO_URL') }}' -user={{ lookup('env','KILLBILL_DAO_USER') }} -password={{ lookup('env','KILLBILL_DAO_PASSWORD') }}
flyway_owner: root
flyway_group: root

# Extra JVM properties (e.g. -Dlogback.configurationFile={{ kb_config_dir }}/logback.xml)
kaui_system_properties: ''
kb_system_properties: ''

# Tomcat and JVM properties -- recommended defaults
jvm_initial_memory: 512m
jvm_max_memory: 2G
jvm_jdwp_port: 12345
jvm_jdwp_server: y
jvm_survivor_ratio: 10
jvm_jmx_port: 8000
tomcat_port: 8080
tomcat_shutdown_port: 8005
tomcat_max_threads: 100
tomcat_max_idle_time: 30000
tomcat_min_spare_threads: 4
tomcat_connection_timeout: 20000
tomcat_unload_delay: 31000
log4jdbc_sqltiming_error_threshold: 1000
