---
- name: Install Flyway
  hosts: all
  tasks:
    - name: Setup Ruby
      import_tasks: roles/common/tasks/main.yml
    - name: Install Flyway
      import_tasks: roles/migrations/tasks/flyway.yml
