---
- name: Deploy Kill Bill
  hosts: all
  vars:
    catalina_base: /var/lib/tomcat
    tomcat_owner: tomcat
    tomcat_group: tomcat
    kpm_install_dir: /opt
    kpm_version: 0.6.1
    kpm_path: "{{ kpm_install_dir }}/kpm-{{ kpm_version }}-linux-{{ ansible_architecture }}"
    kpm_yml: /var/lib/killbill/kpm.yml
    kb_config_dir: /var/lib/killbill
    kb_plugins_dir: /var/lib/killbill/bundles
  tasks:
    - name: setup Ruby
      import_tasks: roles/common/tasks/main.yml
    - name: setup Tomcat
      import_tasks: roles/tomcat/tasks/main.yml
    - name: install Kill Bill
      import_tasks: roles/killbill/tasks/main.yml
