---
- name: Deploy Kill Bill
  hosts: all
  tasks:
    - name: Setup Ruby
      import_tasks: roles/common/tasks/main.yml
    - name: Setup Tomcat
      import_tasks: roles/tomcat/tasks/main.yml
    - name: Install Kill Bill
      import_tasks: roles/killbill/tasks/main.yml
