---
- name: Deploy KPM
  hosts: all
  vars:
    kpm_install_dir: /opt
    nexus_url: https://oss.sonatype.org
    nexus_repository: releases
    kpm_version: 0.6.1
    kpm_path: "{{ kpm_install_dir }}/kpm-{{ kpm_version }}-linux-{{ ansible_architecture }}"
  become: yes
  tasks:
    - name: setup
      import_tasks: roles/common/tasks/main.yml
    - name: install KPM
      import_tasks: roles/kpm/tasks/main.yml
