---
- name: Deploy Tomcat
  hosts: all
  tasks:
    - name: install Tomcat
      ansible.builtin.import_tasks: roles/tomcat/tasks/install.yml
    - name: install Tomcat native libraries
      ansible.builtin.import_tasks: roles/tomcat/tasks/native.yml
      when: java_home is defined
    - name: setup Tomcat
      ansible.builtin.import_tasks: roles/tomcat/tasks/main.yml
