---
- name: Deploy Tomcat
  hosts: all
  tasks:
    - name: Install Tomcat
      import_tasks: roles/tomcat/tasks/install.yml
    - name: Install Tomcat native libraries
      import_tasks: roles/tomcat/tasks/native.yml
      when: java_home is defined
    - name: Setup Tomcat
      import_tasks: roles/tomcat/tasks/main.yml
