---
- name: Ensure Kaui dirs exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "{{ kaui_install_dir }}"
    - "{{ kaui_plugins_dir }}"
  tags: kpm-install

- name: Generate kpm.yml file if needed
  become: true
  template:
    src: "kaui/kpm.yml.j2"
    dest: "{{ kaui_install_dir }}/kpm.yml"
    mode: u=rw,g=r,o=r
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    # If the file already exist, don't clobber it
    force: no
  tags: kpm-install

# Generate Kaui-specific Tomcat configuration files based on environment variables
- name: Generate Tomcat files
  become: true
  template:
    src: "{{ item.src }}/{{ item.name }}.j2"
    dest: "{{ item.dest }}/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    # If the files already exist, don't clobber them
    force: no
  with_items:
    - src: kaui/conf
      name: setenv2.sh
      mode: u=rwx,g=rx,o=rx
      dest: "{{ catalina_base }}/bin"
  tags: tomcat

- name: Check if a ROOT webapp is already installed
  ansible.builtin.stat:
    path: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT"
  register: existing_webapp
  tags: tomcat

# Only run kpm install if there is no exploded webapp already. Otherwise,
# because we will delete the ROOT.war file below, kpm install won't be idempotent
# and always download the war.
# In practice, this means one cannot just update the version in the kpm.yml file
# to update Kaui and re-run the role: one needs to first delete the ROOT directory.
- name: Run KPM install
  become: true
  become_user: "{{ tomcat_owner }}"
  killbill:
    kpm_path: "{{ kpm_path }}"
    kpm_yml: "{{ kaui_kpm_yml }}"
  when: not existing_webapp.stat.exists
  tags: kpm-install

- name: Set correct permissions
  become: true
  ansible.builtin.file:
    path: "{{ kaui_install_dir }}"
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    recurse: yes
  tags: kpm-install

- name: Create ROOT directory to unarchive the WAR
  become: true
  ansible.builtin.file:
    path: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT"
    state: directory
    mode: '0755'

# Expand the WAR to speed up startup
- name: Expand WAR file if not already done
  become: true
  ansible.builtin.command: |
    "{{ java_home }}/bin/jar" -xf ../ROOT.war
  args:
    chdir: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT"
    creates: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT/WEB-INF"
  tags: kaui-logback

# Generate logback configuration files based on environment variables
- name: Copy logback.xml
  become: true
  template:
    src: "kaui/{{ item.name }}.j2"
    # Placing the logback.xml on the classpath of the webapp is the only way to support per-webapp configuration
    dest: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT/WEB-INF/classes/logback.xml"
    mode: u=rw,g=r,o=r
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    force: true
  with_items:
    - name: logback.xml
  tags: kaui-logback

- name: Recursively change ownership for the expanded ROOT
  become: true
  ansible.builtin.file:
    path: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT"
    state: directory
    recurse: yes
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    mode: u=rwX,g=rX,o=rX
  tags: kaui-logback

- name: Remove root archive
  become: true
  ansible.builtin.file:
    path: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT.war"
    state: absent
  tags: kaui-logback
