name: ansible_lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@v25.9.2
        with:
          working_directory: ansible/
          args: "-x role-name,fqcn-builtins,role-name[path],yaml[line-length]"
        env:
          ANSIBLE_LIBRARY: ${{ github.workspace }}/ansible/library
