name: docker_ci

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  # Doesn't matter too much, we just want to verify the build passes
  CURRENT_LTS: '0.24'
  KB_VERSION: '0.24.15'
  KAUI_VERSION: '3.0.20'

jobs:
  docker_ci:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Extract branch name for PR
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
      - name: Build killbill/base:latest
        run: |
          TAG="killbill/base:latest"
          cd docker/templates/base/latest
          DOCKER_BUILDKIT=1 docker build --no-cache -t $TAG -f Dockerfile --build-arg KILLBILL_CLOUD_VERSION=$BRANCH_NAME .
      - name: Build latest images
        run: |
          cd docker
          make -e TARGET=kaui -e VERSION=latest rebuild
          make -e TARGET=killbill VERSION=latest rebuild
          make -e TARGET=mariadb VERSION=$CURRENT_LTS rebuild
          make -e TARGET=postgresql VERSION=$CURRENT_LTS rebuild
      - name: Build killbill image
        run: |
          cd docker
          make -e TARGET=killbill VERSION=$KB_VERSION rebuild
      - name: Build kaui image
        run: |
          cd docker
          make -e TARGET=kaui -e VERSION=$KAUI_VERSION rebuild
